### ISSUE TITLE
Review Data Models

### ISSUE THREAD

**Issue by mwj10** [CSCI-GA-2820-SP23-003/customers#4]
**As a** Quality Insurance **I need** to review the Customers Information Model **So that** developers can either proceed and publish it or makes necessary changes before committing to the design

**Comment by sreevishnu211** [comment]
**As a** developer
**I need** feedback on the Customer and Address model
**So that** I can get a second opinion on the model.
   
 ### Details and Assumptions
The Customer Information Model need to accommodate:
- First Name
- Last Name
- Mobile Number
   
The Address model need to accommodate:
- Street
- City
- State
- Pincode

 ### Acceptance Criteria  
Feedback on the Customer and Address model.
