### ISSUE TITLE
Add and Implement Query routes for Address fields to list methods for Customers

### ISSUE THREAD

**Issue by ayushjainid** [CSCI-GA-2820-SP23-003/customers#75]
**As a** Customer Service Manager/API User
**I need** the Query ability in list methods for Customers for address-fields
**So that** I can retrieve the Customers with specific addresses
   
 ### Details and Assumptions
 * Database Model for Addresses is as per #23
 * Should allow to query for street, country, pin_code, customer_id, state.
 * Should return a list of customers matching the criteria
 * Should be implemented as a filter on the List method.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is up and running
 When querying for addresses with particular fields
 Then only the customers matching the selected fields/criteria should be returned
```

**Comment by wannabeOG** [comment]
Alright @ayushjainid @Akshama @sreevishnu211 @mwj10 where do we want to implement the query:

There are currently two options:

1. We implement the query at the base level (/customers/?query='NY' for instance). In this case, we would be able to get all the addresses in our database with state = 'NY' but I guess then the logic for this would exist in the LIST method for customers itself. Also a bit more complex to implement since we would have to get all the customers and then check against their corresponding addresses. 
1. Implement at the customer level; a bit more straightforward I guess since we would only filter for addresses with state NY for a particular customer but this would require changes being made to the `models.py` code since currently, I believe the addresses are returned irrespective of the customer id. 

Lemme know what you guys think about it.

**Comment by Akshama** [comment]
Discussed over Slack and with Prof, we implemented the first option, listing all customers with all their addresses which have atleast one address matching the query field.
Updated the story description with the above understanding.
